### ISSUE TITLE
lost sign

### ISSUE THREAD

**Issue by iliaishacked** [pawelmorawiecki/Interval_bound_propagation#1]
It seems that you have lost a sign in your linear calculation. 

https://github.com/pawelmorawiecki/Interval_bound_propagation/blob/de525e3300750abf85f92833ee61f65f1ea6c3eb/utils.py#L40

**Comment by pawelmorawiecki** [comment]
Hi,
Sorry, but i don't get your remark. This line computes upper bound for linear layer.

First you take all positive weights (layer.weight.clamp(min=0)) and multiply them with u. Then you take all negative weights (layer.weight.clamp(max=0)) and multiply them with l. This way you're sure  this is the "worst case" scenario --- u_ can not be any bigger than this.

**Comment by iliaishacked** [comment]
Yup, you are right. I guess it is about time to go to sleep -- I saw min instead of max :)
